### ISSUE TITLE
install.batのAPP_DIRの修正または注記の追加

### ISSUE THREAD

**Issue by tuncaa** [AonekoSS/SDPlugin#29]
v0.5を使用させていただいています。
付属のinstall.batについてクリスタ1.10.13以降のバージョンの場合は
以下のURLの通りプラグインのインストールフォルダが変更となっています。

C:\Users\(ユーザー名)\Documents\CELSYS
から
C:\Users\(ユーザー名)\AppData\Roaming\CELSYSUserData\CELSYS

https://support.clip-studio.com/ja-jp/faq/articles/20210039

Ver.3.1.4環境でinstall.bat実行後に公式のユーザーデータフォルダーの移動手順を
実施したところ手動作成した場合のフォルダは自動では移動を行えないようです。
使用者がフォルダのコピー等を行う必要があるためinstall.batに注記いただければ幸いです。

念のため環境情報は以下の通りです。
Application: CLIP STUDIO PAINT EX
Version: 3.1.4
Build Number: 202409181008
OS: Windows
OS Version: 10.0
OS Build Number: 22631

**Comment by AonekoSS** [comment]
情報ありがとうございます。
そうですね…… install.bat 内でバージョンを聞いて、インストール先を切り替えるようにしてみようかと思います。
